name: 'marius'
description: 'build a docker container for marius'
inputs:
  version:
    description: 'build version'
    required: true
    default: '1.0'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}